<?php

namespace TwbBundle;

use Laminas\ServiceManager\Factory\InvokableFactory;

return [
    'twbbundle' => [
        'ignoredViewHelpers' => [
            'file',
            'checkbox',
            'radio',
            'submit',
            'multi_checkbox',
            'static',
            'button',
            'reset'
        ],
        'type_map' => [],
        'class_map' => [],
    ],
    'service_manager' => [
        'factories' => [
            Options\ModuleOptions::class => Options\Factory\ModuleOptionsFactory::class,
        ],
    ],
    'view_helpers' => [
        'aliases' => [
            'form'                       => Form\View\Helper\TwbBundleForm::class,
            'Form'                       => Form\View\Helper\TwbBundleForm::class,
            'form_submit'                => Form\View\Helper\TwbBundleFormButton::class,
            'formsubmit'                 => Form\View\Helper\TwbBundleFormButton::class,
            'formSubmit'                 => Form\View\Helper\TwbBundleFormButton::class,
            'FormSubmit'                 => Form\View\Helper\TwbBundleFormButton::class,
            'formbutton'                 => Form\View\Helper\TwbBundleFormButton::class,
            'form_button'                => Form\View\Helper\TwbBundleFormButton::class,
            'formButton'                 => Form\View\Helper\TwbBundleFormButton::class,
            'FormButton'                 => Form\View\Helper\TwbBundleFormButton::class,
            'formcheckbox'               => Form\View\Helper\TwbBundleFormCheckbox::class,
            'form_checkbox'              => Form\View\Helper\TwbBundleFormCheckbox::class,
            'formCheckbox'               => Form\View\Helper\TwbBundleFormCheckbox::class,
            'FormCheckbox'               => Form\View\Helper\TwbBundleFormCheckbox::class,
            'formcollection'             => Form\View\Helper\TwbBundleFormCollection::class,
            'form_collection'            => Form\View\Helper\TwbBundleFormCollection::class,
            'formCollection'             => Form\View\Helper\TwbBundleFormCollection::class,
            'FormCollection'             => Form\View\Helper\TwbBundleFormCollection::class,
            'form_element'               => Form\View\Helper\TwbBundleFormElement::class,
            'formelement'                => Form\View\Helper\TwbBundleFormElement::class,
            'formElement'                => Form\View\Helper\TwbBundleFormElement::class,
            'FormElement'                => Form\View\Helper\TwbBundleFormElement::class,
            'form_element_errors'        => Form\View\Helper\TwbBundleFormElementErrors::class,
            'formelementerrors'          => Form\View\Helper\TwbBundleFormElementErrors::class,
            'formElementErrors'          => Form\View\Helper\TwbBundleFormElementErrors::class,
            'FormElementErrors'          => Form\View\Helper\TwbBundleFormElementErrors::class,
            'formrow'                    => Form\View\Helper\TwbBundleFormRow::class,
            'form_row'                   => Form\View\Helper\TwbBundleFormRow::class,
            'formRow'                    => Form\View\Helper\TwbBundleFormRow::class,
            'FormRow'                    => Form\View\Helper\TwbBundleFormRow::class,
            'form_multi_checkbox'        => Form\View\Helper\TwbBundleFormMultiCheckbox::class,
            'formmulticheckbox'          => Form\View\Helper\TwbBundleFormMultiCheckbox::class,

            'label'                      => View\Helper\TwbBundleLabel::class,

            'alert' => View\Helper\TwbBundleAlert::class,
            'form_alert' => View\Helper\TwbBundleAlert::class,
            'formalert' => View\Helper\TwbBundleAlert::class,
            'badge' => View\Helper\TwbBundleBadge::class,
            'form_badge' => View\Helper\TwbBundleBadge::class,
            'formbadge' => View\Helper\TwbBundleBadge::class,
            'button_group' => View\Helper\TwbBundleButtonGroup::class,
            'buttonGroup' => View\Helper\TwbBundleButtonGroup::class,
            'form_buttonGroup' => View\Helper\TwbBundleButtonGroup::class,
            'formbuttonGroup' => View\Helper\TwbBundleButtonGroup::class,
            'dropdown' => View\Helper\TwbBundleDropDown::class,
            'dropDown' => View\Helper\TwbBundleDropDown::class,
            'form_dropdown' => View\Helper\TwbBundleDropDown::class,
            'formdropDown' => View\Helper\TwbBundleDropDown::class,

            'form_static' => Form\View\Helper\TwbBundleFormStatic::class,
            'formstatic' => Form\View\Helper\TwbBundleFormStatic::class,
            'form_errors' => Form\View\Helper\TwbBundleFormErrors::class,
            'formerrors' => Form\View\Helper\TwbBundleFormErrors::class,
            'glyphicon' => View\Helper\TwbBundleGlyphicon::class,
            'form_glyphicon' => View\Helper\TwbBundleGlyphicon::class,
            'formglyphicon' => View\Helper\TwbBundleGlyphicon::class,
            'fontAwesome' => View\Helper\TwbBundleFontAwesome::class,
            'form_fontAwesome' => View\Helper\TwbBundleFontAwesome::class,
            'formfontAwesome' => View\Helper\TwbBundleFontAwesome::class,

            'navigation' => View\Helper\Navigation::class,
            'Navigation' => View\Helper\Navigation::class,
            'laminasviewhelpernavigation'  => View\Helper\Navigation::class,

            // Legacy Zend Framework aliases
            \Zend\Form\View\Helper\Form::class                         => Form\View\Helper\TwbBundleForm::class,
            \Zend\Form\View\Helper\FormButton::class                   => Form\View\Helper\TwbBundleFormButton::class,
            \Zend\Form\View\Helper\FormCheckbox::class                 => Form\View\Helper\TwbBundleFormCheckbox::class,
            \Zend\Form\View\Helper\FormCollection::class               => Form\View\Helper\TwbBundleFormCollection::class,
            \Zend\Form\View\Helper\FormElement::class                  => Form\View\Helper\TwbBundleFormElement::class,
            \Zend\Form\View\Helper\FormElementErrors::class            => Form\View\Helper\TwbBundleFormElementErrors::class,
            \Zend\Form\View\Helper\FormLabel::class                    => View\Helper\TwbBundleLabel::class,
            \Zend\Form\View\Helper\FormMultiCheckbox::class            => Form\View\Helper\TwbBundleFormMultiCheckbox::class,
            \Zend\Form\View\Helper\FormRadio::class                    => Form\View\Helper\TwbBundleFormRadio::class,
            \Zend\Form\View\Helper\FormRow::class                      => Form\View\Helper\TwbBundleFormRow::class,
        ],
        'factories' => [
            Form\Element\StaticElement::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleForm::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormButton::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormCheckbox::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormCollection::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormElementErrors::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormErrors::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormMultiCheckbox::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormRadio::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormRow::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormStatic::class => InvokableFactory::class,
            Form\View\Helper\TwbBundleFormElement::class => Form\View\Helper\Factory\TwbBundleFormElementFactory::class,

            View\Helper\Navigation::class => Navigation\View\NavigationHelperFactory::class,
            View\Helper\TwbBundleAlert::class => InvokableFactory::class,
            View\Helper\TwbBundleBadge::class => InvokableFactory::class,
            View\Helper\TwbBundleButtonGroup::class => InvokableFactory::class,
            View\Helper\TwbBundleDropDown::class => InvokableFactory::class,
            View\Helper\TwbBundleFontAwesome::class => InvokableFactory::class,
            View\Helper\TwbBundleGlyphicon::class => InvokableFactory::class,
            View\Helper\TwbBundleLabel::class => InvokableFactory::class,
        ],
    ],
];
